### ISSUE TITLE
Issue when load dataset

### ISSUE THREAD

**Issue by kesungda1920** [phiyodr/dacl10k-toolkit#7]
Hello author, I have some issues when loading Dataset, I try 2 cases:
- Default usage of Dacl10kDataset: all pixel values ​​of mask = 0
- Prefetched: I use Google Colab Pro, but it needs a lot of RAM, I only run ok with validation dataset and its storage locally is  3GB, and I can't run with train dataset although I use TPU with 322 GB RAM
-----
Could you check it for me? Thank you

**Comment by phiyodr** [comment]
Hi, thanks for your interest in dacl10k.

1. Please provide reproducible code so that I can check for issues. Code at [default usage](https://github.com/phiyodr/dacl10k-toolkit?tab=readme-ov-file#default-usage-of-dacl10kdataset) gives me masks with values 0 and 1.
2. I run the code on a 32GB GPU (Nvidia V100), at least that is working. If your GPU memory is not large enough, please run code without prefetching.

**Comment by kesungda1920** [comment]
![image](https://github.com/user-attachments/assets/cbfa3f0f-a1da-4a65-861b-a0df5be9ca75)
I have a GPU, so I use case 2. My image shows that this code only runs with the CPU and RAM (the code refers to your README). When it reaches max RAM, it will stop. I don't clearly understand your reply because it doesn't use a GPU, while you mention running code prefetching if there is enough GPU VRAM.

**Comment by phiyodr** [comment]
I fixed a bug. It is now working?
You can also reduce image and mask size (default is quite large with `(512, 512)`).

You do not need to prefetch data (this is done in CPU). 
You can also just do `img, mask = dataset[100]` to load one sample (and store that one). Or use `Dacl10kDataset` in a `DataLoader`.

**Comment by kesungda1920** [comment]
![image](https://github.com/user-attachments/assets/6a6a7229-524c-4fad-bf3c-9c8fd34586d9)
With case prefetch, I still have an issue, Can you give me your env?

**Comment by phiyodr** [comment]
It works on my 32GB RAM machine. I cannot reproduce your issue. 

- You can still reduce image and mask size in `Dacl10kDataset`. 
- Prefetching is not mandatory, you can still use the code without running `.run_prefetching()`

**Comment by kesungda1920** [comment]
Oh, Thank you
